environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

image: Visual Studio 2017 Preview

init:
  - cmd: git config --global core.autocrlf true
  
build_script:
  - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq $true) {
            $VersionSuffix = ""
        }
        else {
            $VersionSuffix = "ci" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(4, "0") + "-" + $env:APPVEYOR_REPO_BRANCH.Replace("/", "-")
        }
  - ps: .\build.ps1 -VersionSuffix $VersionSuffix

artifacts:
- path: '*.nupkg'

# Deploy every successful build (except PRs) to development feed
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

deploy:
  # Create a GitHub release for every tag
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: "See milestone for changes"
    # Draft and Prerelease can be removed after testing
    draft: true
    prerelease: true
    auth_token:
      # This will need to be updated with secure token generated with OpenTracing account
      secure: JU9H+A+WwAtz4Xkcd/50N239EiX1o7OpEnmtiQGayR+Zc2ZHF8xrcPMRelHyJwZL 
    on:
      appveyor_repo_tag: true
